services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "mysql://prisma:prisma@db:3306/prisma"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: prisma
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - prisma-db:/var/lib/mysql
volumes:
  prisma-db:
